remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

# theme: jekyll-theme-minimal
title: Nordic Electrochemistry
description: Nordic Electrochemistry on Github!
logo: /assets/img/logo.png

author:
  name: Gustav Wiberg
  email: info@nordicec.com
